### ISSUE TITLE
Gatsby 3, or Cannot destructure property 'createNode' of 'boundActionCreators' 

### ISSUE THREAD

**Issue by k4y4k** [Necmttn/gatsby-source-trello#10]
I don't know too much about the move from Gatsby 2 -> 3, but I do know that this error:

```
 ERROR #11321  PLUGIN

"gatsby-source-trello" threw an error while running the sourceNodes lifecycle:

Cannot destructure property 'createNode' of 'boundActionCreators' as it is undefined.

  13 |   verboseOutput = false
  14 | }) => {
> 15 |   const { createNode } = boundActionCreators;
     |           ^
  16 |   _verbose = verboseOutput;
  17 |   _apiKey = apiKey;
  18 |   _secret = secret;

File: node_modules/gatsby-source-trello/gatsby-node.js:15:11
``` 

is probably related. Are there any plans to update? Are you open to PRs?

**Comment by Necmttn** [comment]
Yeah feel free to create PR for it, I will help to merge in. Currently I'm not using gatsby so haven't had chance to upgrade for gatsby 3

**Comment by k4y4k** [comment]
no wakkas, I'll get on it soon. 
@samdoidge I see you left a :+1: down there, what's your usecase if you don't mind?

**Comment by samdoidge** [comment]
@k4y4k Haha you've made me think. I believe I found this issue after moving to Gatsby 3, however not with this package. I'm afraid I can't provide more info

**Comment by k4y4k** [comment]
No worries :sunglasses:

**Comment by k4y4k** [comment]
closing - I no longer use Gatsby, don't have the bandwidth to investigate/fix, and nobody else has chimed in to say it also affects them.
